TheBookLounge.Web/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TheBookLounge.DataAccess;
using TheBookLounge.DataAccess.Models;
using TheBookLounge.Web.Helpers;

namespace TheBookLounge.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public BookController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        public async Task<IActionResult> List(string searchString)
        {
            IEnumerable<Book> books = await _applicationDbContext.Books
                .Include(a => a.Author)
                .OrderBy(b => b.Title)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                // Search by title, author and genre
                // The Search is case insensitive
                books = books.Where(s => s.Title.Contains(searchString, StringComparison.OrdinalIgnoreCase)
                                         || s.Author.AuthorName.Contains(searchString, StringComparison.OrdinalIgnoreCase)
                                         || s.Genre.Contains(searchString, StringComparison.OrdinalIgnoreCase));

                TempData["search"] = searchString;
            }

            return View(books);
        }

        // GET: BookController/Details/5
        public async Task<IActionResult> Details(int ? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var book = await _applicationDbContext.Books
                .Include(c => c.Author)
                .FirstOrDefaultAsync(b => b.BookId == id);

            if (book == null)
            {
                return NotFound($"Book id {id} does not exist");
            }

            return View(book);
        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Book book, Author author)
        {
            var status = BookStatus.Creating;

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            
            var authors = await _applicationDbContext.Authors.ToListAsync();
            var sameAuthor = authors.FirstOrDefault(a => a.AuthorName == author.AuthorName);

            var newBook = new Book();

            if (sameAuthor != null)
            {

                newBook.Title = book.Title;
                newBook.ISBN = book.ISBN;
                newBook.Genre = book.Genre;
                newBook.IsAvailable = book.IsAvailable;
                newBook.AuthorId = sameAuthor.AuthorId;

            }
            else
            {

                newBook.Title = book.Title;
                newBook.ISBN = book.ISBN;
                newBook.Genre = book.Genre;
                newBook.IsAvailable = book.IsAvailable;
                newBook.Author = new Author {AuthorName = author.AuthorName};

            };

            await _applicationDbContext.Books.AddAsync(newBook);

            await UpdateCopies(newBook, status);

            await _applicationDbContext.SaveChangesAsync();

            TempData["message-create"] = "The book list has been updated successfully.";
            TempData["create"] = "Create";

            return RedirectToAction("Details", new { id = newBook.BookId });
                
        }

        // GET: HomeController1/Edit/5
        public async Task<ActionResult> Edit(int ? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var book = await _applicationDbContext.Books
                .Include(c => c.Author)
                .FirstOrDefaultAsync(b => b.BookId == id);

            if (book == null)
            {
                return NotFound($"Book id {id} does not exist");
            }

            return View(book);
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Book book)
        {
            var status = BookStatus.Editing;

            if (book == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            
            var bookToUpdate =  _applicationDbContext.Books
                .FirstOrDefault(b => b.BookId == book.BookId);

            if (bookToUpdate == null)
            {
                return NotFound($"Book id {book.BookId} does not exist");
            }

            bookToUpdate.Title = book.Title;
            bookToUpdate.ISBN = book.ISBN;
            bookToUpdate.Genre = book.Genre;
            bookToUpdate.IsAvailable = book.IsAvailable;

            _applicationDbContext.Books.Update(bookToUpdate);

            await UpdateCopies(bookToUpdate, status);

            await _applicationDbContext.SaveChangesAsync();

            TempData["message-edit"] = "The book has been modified.";
            TempData["edit"] = "Edit";

            return RedirectToAction("Details", new { id = book.BookId });
        }

        // GET: BookController/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(int ? id)
        {
            var status = BookStatus.Deleting;

            if (id == null)
            {
                return BadRequest();
            }

            var selectedBook = await _applicationDbContext.Books
                .Include(c => c.Author)
                .FirstOrDefaultAsync(b => b.BookId == id);

            if (selectedBook == null)
            {
                return NotFound($"Book id {id} does not exist");
            }

            _applicationDbContext.Books.Remove(selectedBook);

            await UpdateCopies(selectedBook, status);

            await _applicationDbContext.SaveChangesAsync();

            TempData["message-delete"] = "The book has been successfully deleted from the system.";

            return RedirectToAction("List");
        }

        private async Task UpdateCopies(Book book, BookStatus status)
        {
            var sameBooks = await _applicationDbContext.Books
                .Where(b => b.Title.Contains(book.Title) && b.AuthorId == book.AuthorId)
                .Select(x => x).ToListAsync();

            switch (status)
            {
                case BookStatus.Creating:
                    sameBooks.Add(book);
                    await _applicationDbContext.SaveChangesAsync();
                    break;
                case BookStatus.Deleting:
                    sameBooks.Remove(book);
                    break;
                case BookStatus.Editing:
                    break;
            }

            var totalCopies = sameBooks.Count();
            var availableCopies = sameBooks.Count(b => b.IsAvailable == true);

            foreach (var item in sameBooks)
            {
                item.TotalCopies = totalCopies;
                item.AvailableCopies = availableCopies;
            }

            _applicationDbContext.Books.UpdateRange(sameBooks);
        }
    }
}

TheBookLounge.Web/Views/Book/Create.cshtml
@model AddBookViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Add Book</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" role="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.ISBN" class="control-label"></label>
                <input asp-for="Book.ISBN" placeholder=" X-XXX-XXXXX-X or XXX-X-XXX-XXXXX-X " class="form-control" />
                <span asp-validation-for="Book.ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author.AuthorName" class="control-label"></label>
                <input asp-for="Author.AuthorName" class="form-control" />
                <span asp-validation-for="Author.AuthorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Genre" class="control-label"></label>
                <input asp-for="Book.Genre" class="form-control" />
                <span asp-validation-for="Book.Genre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Book.IsAvailable" /> @Html.DisplayNameFor(model => model.Book.IsAvailable)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Add book" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to list</a>
</div>

<br />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TheBookLounge.Web/Views/Book/Details.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding
@model Book
@{
    ViewData["Title"] = "Book details";

    ViewData["Message-edit"] = TempData["message-edit"];
    ViewData["Edit"] = TempData["edit"];

    ViewData["Message-create"] = TempData["message-create"];
    ViewData["Create"] = TempData["create"];

}

@if (ViewData["Message-edit"] != null || ViewData["Message-create"] != null)
{
    @if (ViewData["Edit"] != null)
    {
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Book edited!</h4>
            @ViewData["Message-edit"]
        </div>
    }
    else
    {
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Book added to the system!!</h4>
            @ViewData["Message-create"]
        </div>
    }
}

<h1> @ViewData["Title"]</h1>
<br/>
<p><h3>@Model.Title</h3></p>
<p><strong>Author: </strong>@Model.Author.AuthorName</p>
<p><strong>ISBN: </strong>@Model.ISBN</p>
<p><strong>Genre: </strong>@Model.Genre</p>

@if (@Model.IsAvailable)
{
    <p><strong>Available: </strong>Yes</p>
}
else
{
    <p><strong>Available: </strong>No</p>
}


<p>
    <a class="btn btn-primary"
       asp-controller="Book"
       asp-action="Edit"
       asp-route-id="@Model.BookId">Edit</a>
</p>
<br />
<a asp-action="List">Back to List</a>
<br />
<br />

@*TODO: Button to add book to check in*@

TheBookLounge.Web/Views/Book/Edit.cshtml
@model Book

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" role="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BookId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <input type="hidden" asp-for="AuthorId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <a asp-action="List">Back to List</a>
    </div>
</div>
<br />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TheBookLounge.Web/Views/Book/List.cshtml
@using Microsoft.CodeAnalysis.CSharp.Syntax
@model IEnumerable<Book>

@{int i = 1;}

@{
    ViewData["Title"] = "List";
    ViewData["Message"] = TempData["message-delete"];
    ViewData["Search"] = TempData["search"];
}

<h1>Book list</h1>

@if (ViewData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Book deleted!</h4>
        @ViewData["Message"]
    </div>
}

<div class="row">
    <div class="col">
        <p>
            <a asp-action="Create" asp-controller="Book">Add Book</a>
        </p>
    </div>
    <div class="col">
        <form asp-controller="Book" asp-action="List">
            <p align="right">

                @if (ViewData["Search"] != null)
                {
                    <input type="search" id="SearchBox" name="SearchString" placeholder=@ViewData["Search"]>
                    <input type="submit" value="Search" class="btn btn-primary" size="50" />
                }
                else
                {
                    <input type="search" id="SearchBox" name="SearchString" placeholder="Book/Author/Genre">
                    <input type="submit" value="Search" class="btn btn-primary" size="50" />
                }

            </p>
        </form>
    </div>

</div>
<table class="table">
    <thead>
        <tr>
            <th>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author.AuthorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @*Column with int indicating order*@
                    <span><b>@(i++)</b></span>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author.AuthorName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ISBN)
                </td>
                <td>
                    @if (item.IsAvailable)
                    {
                        <p>Yes</p>
                    }
                    else
                    {
                        <p>No</p>
                    }
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.BookId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.BookId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.BookId },
                        new { onclick = "return confirm('Are you sure you wish to delete this book from the system?');" })
                </td>
            </tr>
        }
    </tbody>
</table>
<br/>